// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mortgage.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20251219205655_inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mortgagee", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("First_Instalment_Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Instalments")
                        .HasColumnType("float");

                    b.Property<double>("Interest_Rate_In_Percent")
                        .HasColumnType("float");

                    b.Property<double>("Interest_Sum")
                        .HasColumnType("float");

                    b.Property<double>("Loan_Ammount")
                        .HasColumnType("float");

                    b.Property<double>("Total_Sum")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Mortgages");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data_Płatności")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kwota_Kapitału")
                        .HasColumnType("float");

                    b.Property<double>("Kwota_Odsetek")
                        .HasColumnType("float");

                    b.Property<int>("Numer_Raty")
                        .HasColumnType("int");

                    b.Property<double>("Pozostało_Do_Spłaty")
                        .HasColumnType("float");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Wysokość_Raty")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Generation_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number_Of_Payments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("Schedule", "Schedule")
                        .WithMany("Payments")
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Schedule", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
